services:
  api:
    build: .
    container_name: farmacia_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: farmacia_postgres
    restart: always
    environment:
      POSTGRES_USER: aurora_admin
      POSTGRES_PASSWORD: super_senha_segura
      POSTGRES_DB: farmacia_db
    ports:
      - "4242:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: