"""refactor: separa catalogo de ofertas locais

Revision ID: 1b5b9f702ce6
Revises: 8e1b9172e337
Create Date: 2026-04-08 13:50:31.448811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b5b9f702ce6'
down_revision: Union[str, Sequence[str], None] = '8e1b9172e337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=13), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('principio_ativo', sa.String(length=150), nullable=False),
    sa.Column('laboratorio', sa.String(length=100), nullable=False),
    sa.Column('exige_receita', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogo_base'))
    )
    op.create_index(op.f('ix_catalogo_base_codigo_barras'), 'catalogo_base', ['codigo_barras'], unique=True)
    op.create_index(op.f('ix_catalogo_base_id'), 'catalogo_base', ['id'], unique=False)
    op.create_index(op.f('ix_catalogo_base_laboratorio'), 'catalogo_base', ['laboratorio'], unique=False)
    op.create_index(op.f('ix_catalogo_base_nome'), 'catalogo_base', ['nome'], unique=False)
    op.create_index(op.f('ix_catalogo_base_principio_ativo'), 'catalogo_base', ['principio_ativo'], unique=False)
    op.create_table('ofertas_farmacia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('url_origem', sa.String(length=500), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('farmacia_id', sa.Integer(), nullable=False),
    sa.Column('catalogo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_id'], ['catalogo_base.id'], name=op.f('fk_ofertas_farmacia_catalogo_id_catalogo_base')),
    sa.ForeignKeyConstraint(['farmacia_id'], ['farmacias.id'], name=op.f('fk_ofertas_farmacia_farmacia_id_farmacias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ofertas_farmacia'))
    )
    op.create_index(op.f('ix_ofertas_farmacia_id'), 'ofertas_farmacia', ['id'], unique=False)
    op.create_index(op.f('ix_ofertas_farmacia_url_origem'), 'ofertas_farmacia', ['url_origem'], unique=True)
    op.drop_index(op.f('ix_medicamentos_codigo_barras'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_id'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_laboratorio'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_nome'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_principio_ativo'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_url_origem'), table_name='medicamentos')
    op.drop_table('medicamentos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo_barras', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('principio_ativo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('laboratorio', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('exige_receita', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('quantidade_estoque', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('disponivel', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('url_origem', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('imagem_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('farmacia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['farmacia_id'], ['farmacias.id'], name=op.f('fk_medicamentos_farmacia_id_farmacias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicamentos'))
    )
    op.create_index(op.f('ix_medicamentos_url_origem'), 'medicamentos', ['url_origem'], unique=True)
    op.create_index(op.f('ix_medicamentos_principio_ativo'), 'medicamentos', ['principio_ativo'], unique=False)
    op.create_index(op.f('ix_medicamentos_nome'), 'medicamentos', ['nome'], unique=False)
    op.create_index(op.f('ix_medicamentos_laboratorio'), 'medicamentos', ['laboratorio'], unique=False)
    op.create_index(op.f('ix_medicamentos_id'), 'medicamentos', ['id'], unique=False)
    op.create_index(op.f('ix_medicamentos_codigo_barras'), 'medicamentos', ['codigo_barras'], unique=True)
    op.drop_index(op.f('ix_ofertas_farmacia_url_origem'), table_name='ofertas_farmacia')
    op.drop_index(op.f('ix_ofertas_farmacia_id'), table_name='ofertas_farmacia')
    op.drop_table('ofertas_farmacia')
    op.drop_index(op.f('ix_catalogo_base_principio_ativo'), table_name='catalogo_base')
    op.drop_index(op.f('ix_catalogo_base_nome'), table_name='catalogo_base')
    op.drop_index(op.f('ix_catalogo_base_laboratorio'), table_name='catalogo_base')
    op.drop_index(op.f('ix_catalogo_base_id'), table_name='catalogo_base')
    op.drop_index(op.f('ix_catalogo_base_codigo_barras'), table_name='catalogo_base')
    op.drop_table('catalogo_base')
    # ### end Alembic commands ###
