"""add_categorias_e_enriquecimento_ao_catalogo

Revision ID: 1de74e4279f7
Revises: 1b5b9f702ce6
Create Date: 2026-05-20 11:32:24.558777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1de74e4279f7'
down_revision: Union[str, Sequence[str], None] = '1b5b9f702ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_precos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('farmacia_id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmacia_id'], ['farmacias.id'], name=op.f('fk_historico_precos_farmacia_id_farmacias')),
    sa.ForeignKeyConstraint(['medicamento_id'], ['catalogo_base.id'], name=op.f('fk_historico_precos_medicamento_id_catalogo_base')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historico_precos'))
    )
    op.create_index(op.f('ix_historico_precos_data_registro'), 'historico_precos', ['data_registro'], unique=False)
    op.create_index(op.f('ix_historico_precos_id'), 'historico_precos', ['id'], unique=False)
    op.add_column('catalogo_base', sa.Column('categorias', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogo_base', 'categorias')
    op.drop_index(op.f('ix_historico_precos_id'), table_name='historico_precos')
    op.drop_index(op.f('ix_historico_precos_data_registro'), table_name='historico_precos')
    op.drop_table('historico_precos')
    # ### end Alembic commands ###
