"""separa sku interno do ean e padroniza name_search

Revision ID: 615cab55047f
Revises: 1de74e4279f7
Create Date: 2026-05-22 17:43:20.899325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615cab55047f'
down_revision: Union[str, Sequence[str], None] = '1de74e4279f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ofertas_farmacia', sa.Column('sku_interno', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_ofertas_farmacia_sku_interno'), 'ofertas_farmacia', ['sku_interno'], unique=False)

    op.alter_column('catalogo_base', 'codigo_barras',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=14),
               nullable=True,
               existing_nullable=False)

    op.alter_column('catalogo_base', 'nome', new_column_name='name_search')
    op.drop_index('ix_catalogo_base_nome', table_name='catalogo_base')
    op.create_index(op.f('ix_catalogo_base_name_search'), 'catalogo_base', ['name_search'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogo_base_name_search'), table_name='catalogo_base')
    op.create_index('ix_catalogo_base_nome', 'catalogo_base', ['nome'], unique=False)
    op.alter_column('catalogo_base', 'name_search', new_column_name='nome')

    op.alter_column('catalogo_base', 'codigo_barras',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=13),
               nullable=False,
               existing_nullable=True)

    op.drop_index(op.f('ix_ofertas_farmacia_sku_interno'), table_name='ofertas_farmacia')
    op.drop_column('ofertas_farmacia', 'sku_interno')
    # ### end Alembic commands ###
