"""inicializa_tabelas_postgres

Revision ID: 8e1b9172e337
Revises: 
Create Date: 2026-03-30 14:14:47.660409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1b9172e337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmacias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco_completo', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farmacias'))
    )
    op.create_index(op.f('ix_farmacias_cnpj'), 'farmacias', ['cnpj'], unique=True)
    op.create_index(op.f('ix_farmacias_id'), 'farmacias', ['id'], unique=False)
    op.create_index(op.f('ix_farmacias_nome_fantasia'), 'farmacias', ['nome_fantasia'], unique=False)
    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=13), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('principio_ativo', sa.String(length=150), nullable=False),
    sa.Column('laboratorio', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exige_receita', sa.Boolean(), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('url_origem', sa.String(length=500), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('farmacia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmacia_id'], ['farmacias.id'], name=op.f('fk_medicamentos_farmacia_id_farmacias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicamentos'))
    )
    op.create_index(op.f('ix_medicamentos_codigo_barras'), 'medicamentos', ['codigo_barras'], unique=True)
    op.create_index(op.f('ix_medicamentos_id'), 'medicamentos', ['id'], unique=False)
    op.create_index(op.f('ix_medicamentos_laboratorio'), 'medicamentos', ['laboratorio'], unique=False)
    op.create_index(op.f('ix_medicamentos_nome'), 'medicamentos', ['nome'], unique=False)
    op.create_index(op.f('ix_medicamentos_principio_ativo'), 'medicamentos', ['principio_ativo'], unique=False)
    op.create_index(op.f('ix_medicamentos_url_origem'), 'medicamentos', ['url_origem'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicamentos_url_origem'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_principio_ativo'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_nome'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_laboratorio'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_id'), table_name='medicamentos')
    op.drop_index(op.f('ix_medicamentos_codigo_barras'), table_name='medicamentos')
    op.drop_table('medicamentos')
    op.drop_index(op.f('ix_farmacias_nome_fantasia'), table_name='farmacias')
    op.drop_index(op.f('ix_farmacias_id'), table_name='farmacias')
    op.drop_index(op.f('ix_farmacias_cnpj'), table_name='farmacias')
    op.drop_table('farmacias')
    # ### end Alembic commands ###
