"""Add AnvisaMedicamento model

Revision ID: e0c4fa285a00
Revises: 615cab55047f
Create Date: 2026-05-25 17:22:32.239787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c4fa285a00'
down_revision: Union[str, Sequence[str], None] = '615cab55047f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anvisa_medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('principio_ativo', sa.String(), nullable=True),
    sa.Column('laboratorio', sa.String(), nullable=True),
    sa.Column('tarja', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anvisa_medicamentos'))
    )
    op.create_index(op.f('ix_anvisa_medicamentos_ean'), 'anvisa_medicamentos', ['ean'], unique=True)
    op.create_index(op.f('ix_anvisa_medicamentos_id'), 'anvisa_medicamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anvisa_medicamentos_id'), table_name='anvisa_medicamentos')
    op.drop_index(op.f('ix_anvisa_medicamentos_ean'), table_name='anvisa_medicamentos')
    op.drop_table('anvisa_medicamentos')
    # ### end Alembic commands ###
